import type { TaxJurisdictionDTO, TaxRuleDTO } from "./types";

export interface JurisdictionCatalogEntry {
  jurisdiction: TaxJurisdictionDTO;
  defaultRules: Omit<TaxRuleDTO, "id" | "jurisdictionId">[];
}

export const JURISDICTIONS_CATALOG: Record<string, JurisdictionCatalogEntry> = {
  "SA_RIYADH": {
    jurisdiction: {
      id: "jur_sa_riyadh",
      country: "SA",
      region: "Riyadh Province",
      city: "Riyadh",
      name: "Saudi Arabia — Riyadh Municipality",
      currency: "SAR",
      isActive: true,
    },
    defaultRules: [
      {
        taxType: "VAT",
        name: "Saudi Value-Added Tax (VAT)",
        description: "Standard national 15% VAT on hospitality and accommodation services, collected and remitted by the platform.",
        calculationMethod: "PERCENTAGE",
        rate: 15.0,
        amount: null,
        taxableComponents: ["BASE_PRICE", "CLEANING_FEE"],
        remittanceResponsibility: "PLATFORM",
        isSystemManaged: true,
        isInclusive: false,
        longStayExemptionNights: null,
        effectiveFrom: "2020-07-01T00:00:00.000Z",
        effectiveUntil: null,
        version: 1,
        isActive: true,
      },
      {
        taxType: "TOURIST_TAX",
        name: "Riyadh Municipal Tourism Fee",
        description: "Local municipal tourism development fee applied per night of stay.",
        calculationMethod: "AMOUNT_PER_NIGHT",
        rate: null,
        amount: 2500, // SAR 25.00 (in minor units / halalas)
        taxableComponents: ["BASE_PRICE"],
        remittanceResponsibility: "PLATFORM",
        isSystemManaged: true,
        isInclusive: false,
        longStayExemptionNights: 30,
        effectiveFrom: "2024-01-01T00:00:00.000Z",
        effectiveUntil: null,
        version: 1,
        isActive: true,
      },
    ],
  },
  "SA_JEDDAH": {
    jurisdiction: {
      id: "jur_sa_jeddah",
      country: "SA",
      region: "Makkah Province",
      city: "Jeddah",
      name: "Saudi Arabia — Jeddah Municipality",
      currency: "SAR",
      isActive: true,
    },
    defaultRules: [
      {
        taxType: "VAT",
        name: "Saudi Value-Added Tax (VAT)",
        description: "Standard national 15% VAT on hospitality and accommodation services.",
        calculationMethod: "PERCENTAGE",
        rate: 15.0,
        amount: null,
        taxableComponents: ["BASE_PRICE", "CLEANING_FEE"],
        remittanceResponsibility: "PLATFORM",
        isSystemManaged: true,
        isInclusive: false,
        longStayExemptionNights: null,
        effectiveFrom: "2020-07-01T00:00:00.000Z",
        effectiveUntil: null,
        version: 1,
        isActive: true,
      },
      {
        taxType: "TOURIST_TAX",
        name: "Jeddah Tourism Fee",
        description: "Municipal tourism surcharge collected per night.",
        calculationMethod: "AMOUNT_PER_NIGHT",
        rate: null,
        amount: 2000, // SAR 20.00
        taxableComponents: ["BASE_PRICE"],
        remittanceResponsibility: "PLATFORM",
        isSystemManaged: true,
        isInclusive: false,
        longStayExemptionNights: 30,
        effectiveFrom: "2024-01-01T00:00:00.000Z",
        effectiveUntil: null,
        version: 1,
        isActive: true,
      },
    ],
  },
  "SA_NATIONAL": {
    jurisdiction: {
      id: "jur_sa_national",
      country: "SA",
      region: null,
      city: null,
      name: "Saudi Arabia — National Jurisdiction",
      currency: "SAR",
      isActive: true,
    },
    defaultRules: [
      {
        taxType: "VAT",
        name: "Saudi Value-Added Tax (VAT)",
        description: "Standard national 15% VAT on hospitality services.",
        calculationMethod: "PERCENTAGE",
        rate: 15.0,
        amount: null,
        taxableComponents: ["BASE_PRICE", "CLEANING_FEE"],
        remittanceResponsibility: "PLATFORM",
        isSystemManaged: true,
        isInclusive: false,
        longStayExemptionNights: null,
        effectiveFrom: "2020-07-01T00:00:00.000Z",
        effectiveUntil: null,
        version: 1,
        isActive: true,
      },
    ],
  },
  "AE_DUBAI": {
    jurisdiction: {
      id: "jur_ae_dubai",
      country: "AE",
      region: "Emirate of Dubai",
      city: "Dubai",
      name: "United Arab Emirates — Dubai (DTCM)",
      currency: "AED",
      isActive: true,
    },
    defaultRules: [
      {
        taxType: "VAT",
        name: "UAE Value-Added Tax (VAT)",
        description: "National 5% VAT across all short-term rentals.",
        calculationMethod: "PERCENTAGE",
        rate: 5.0,
        amount: null,
        taxableComponents: ["BASE_PRICE", "CLEANING_FEE"],
        remittanceResponsibility: "PLATFORM",
        isSystemManaged: true,
        isInclusive: false,
        longStayExemptionNights: null,
        effectiveFrom: "2018-01-01T00:00:00.000Z",
        effectiveUntil: null,
        version: 1,
        isActive: true,
      },
      {
        taxType: "TOURIST_TAX",
        name: "Tourism Dirham Fee",
        description: "Dubai DTCM Tourism Dirham Fee applied per night of stay (AED 15).",
        calculationMethod: "AMOUNT_PER_NIGHT",
        rate: null,
        amount: 1500, // AED 15.00
        taxableComponents: ["BASE_PRICE"],
        remittanceResponsibility: "PLATFORM",
        isSystemManaged: true,
        isInclusive: false,
        longStayExemptionNights: 30,
        effectiveFrom: "2016-01-01T00:00:00.000Z",
        effectiveUntil: null,
        version: 1,
        isActive: true,
      },
    ],
  },
  "GB_NATIONAL": {
    jurisdiction: {
      id: "jur_gb_national",
      country: "GB",
      region: null,
      city: null,
      name: "United Kingdom — HMRC",
      currency: "GBP",
      isActive: true,
    },
    defaultRules: [
      {
        taxType: "VAT",
        name: "UK Value Added Tax (VAT)",
        description: "Standard 20% VAT on short-term holiday accommodations.",
        calculationMethod: "PERCENTAGE",
        rate: 20.0,
        amount: null,
        taxableComponents: ["BASE_PRICE", "CLEANING_FEE"],
        remittanceResponsibility: "PLATFORM",
        isSystemManaged: true,
        isInclusive: false,
        longStayExemptionNights: 28,
        effectiveFrom: "2020-01-01T00:00:00.000Z",
        effectiveUntil: null,
        version: 1,
        isActive: true,
      },
    ],
  },
  "US_CA_LOS_ANGELES": {
    jurisdiction: {
      id: "jur_us_ca_los_angeles",
      country: "US",
      region: "California",
      city: "Los Angeles",
      name: "United States — Los Angeles, CA",
      currency: "USD",
      isActive: true,
    },
    defaultRules: [
      {
        taxType: "OCCUPANCY_TAX",
        name: "Los Angeles Transient Occupancy Tax (TOT)",
        description: "14% Transient Occupancy Tax collected for stays under 31 consecutive days.",
        calculationMethod: "PERCENTAGE",
        rate: 14.0,
        amount: null,
        taxableComponents: ["BASE_PRICE", "CLEANING_FEE"],
        remittanceResponsibility: "PLATFORM",
        isSystemManaged: true,
        isInclusive: false,
        longStayExemptionNights: 31,
        effectiveFrom: "2020-01-01T00:00:00.000Z",
        effectiveUntil: null,
        version: 1,
        isActive: true,
      },
    ],
  },
  "DEFAULT_GLOBAL": {
    jurisdiction: {
      id: "jur_default_global",
      country: "SA",
      region: null,
      city: null,
      name: "Standard Accommodation Jurisdiction",
      currency: "SAR",
      isActive: true,
    },
    defaultRules: [
      {
        taxType: "VAT",
        name: "Hospitality Value-Added Tax (VAT)",
        description: "Standard 15% VAT on hospitality accommodations.",
        calculationMethod: "PERCENTAGE",
        rate: 15.0,
        amount: null,
        taxableComponents: ["BASE_PRICE", "CLEANING_FEE"],
        remittanceResponsibility: "PLATFORM",
        isSystemManaged: true,
        isInclusive: false,
        longStayExemptionNights: null,
        effectiveFrom: "2020-07-01T00:00:00.000Z",
        effectiveUntil: null,
        version: 1,
        isActive: true,
      },
    ],
  },
};

